#!/bin/bash

cd source
make clean
DESTDIR=/medianet/overlay CXXFLAGS="-march=armv8-a+crc -mfpu=neon-fp-armv8 -mtune=cortex-a53" make -j4
sudo DESTDIR=/medianet/overlay CXXFLAGS="-march=armv8-a+crc -mfpu=neon-fp-armv8 -mtune=cortex-a53" make install
cd ..
