#!/bin/bash

# [mn] medianet Maintenance tunnel

. /medianet/lib/mn_includes
. "$CONF_FILE_MNTUNNEL"

LOCAL_SSH_PORT=22

if [[ -f "$TUNNEL_STATEFILE" ]] ; then

  echo "Starting..."
  $SSH -N \
        -i "$TUNNEL_HOST_KEY" \
        -o UserKnownHostsFile="$TUNNEL_HOST_FINGERPRINT" \
	-o StrictHostKeyChecking=yes \
        -o ExitOnForwardFailure=yes \
	-o ServerAliveInterval=60 \
	-o IdentitiesOnly=yes \
        -p ${TUNNEL_PORT} \
        -l ${TUNNEL_USER} \
        -R ${TUNNEL_PORT_ACCESS}:localhost:${LOCAL_SSH_PORT} \
        -L ${TUNNEL_PORT_CHECK}:localhost:${LOCAL_SSH_PORT} \
        ${TUNNEL_HOST}

  # SSH should keep blocking here, so if we reach the following,
  # something went wrong. Signal failure with unclean exit code.
  echo "Maintenance tunnel died."
  exit 2

else

  echo "Maintenance tunnel deactivated."

fi

exit 0;
