#!/bin/bash

BASEDIR=`dirname $0`

. "$BASEDIR"/../lib/mn_includes

sudo apt-get update
sudo apt-get -y upgrade

cat "$BASEDIR"/../lib/mn_packages | while read line ; do
	for package in $line; do
		if [[ $package == \#* ]] ; then
			# we've found a comment, ignore all that follows on the line:
			break
		else
			echo -n "$package "
		fi
	done
done | xargs -n 32 sudo apt-get -y install 