#!/bin/bash

. /medianet/lib/mn_includes

noroot

OLDWD=`pwd`
DESTDIR="$PREFIX"/overlay
cd "$PREFIX"/custom_builds

if [[ -n "$1" ]] ; then
	TARGET="$1.build"
else
	TARGET=
	for i in $CUSTOM_BUILDS ; do
		TARGET+="$i.build "
	done
fi

scream "Building \"$TARGET\"."

for i in $TARGET; do
  line=`"$READLINK" --canonicalize "$i"`
  WORKDIR=`echo "$line" | "$SED" 's/\.build$//'`
  cd "$WORKDIR"
  scream "********* Compiling $line...\n"
  . "$line" \
    && scream "********* ...$line successfully compiled and installed.\n" \
    || { 
      scream "********* ...$line " 
      failure
    }
  cd ..
done

cd "$OLDWD"
echo "Compiled programs have been installed to $DESTDIR. Deploy with 'sudo $PREFIX/sbin/mn_deploy_overlay' to activate them."
