#!/bin/bash

. /medianet/lib/mn_includes

noroot

function platform_optimisations {
# this works on Raspberry Pis:
        PIMODEL=`cat /proc/device-tree/model | "$TR" -d '\0'`
        if [[ "$PIMODEL" =~ ^Raspberry\ Pi\ Model\ B ]] ; then
                echo -n "$CUSTOM_BUILD_GCCFLAGS_PI1B"
        elif [[ "$PIMODEL" =~ ^Raspberry\ Pi\ 2\ Model\ B ]] ; then
                echo -n "$CUSTOM_BUILD_GCCFLAGS_PI2B"
        elif [[ "$PIMODEL" =~ ^Raspberry\ Pi\ 3\ Model\ B\ Rev ]] ; then
                echo -n "$CUSTOM_BUILD_GCCFLAGS_PI3B"
        elif [[ "$PIMODEL" =~ ^Raspberry\ Pi\ 3\ Model\ B\ Plus ]] ; then
                echo -n "$CUSTOM_BUILD_GCCFLAGS_PI2B"
        elif [[ "$PIMODEL" =~ ^Raspberry\ Pi\ 4\ Model\ B ]] ; then
                echo -n "$CUSTOM_BUILD_GCCFLAGS_PI4B"
        fi
}


OLDWD=`pwd`
DESTDIR="$PREFIX"/overlay
cd "$PREFIX"/custom_builds

if [[ -n "$1" ]] ; then
	TARGET="$1.build"
else
	TARGET=
	for i in $CUSTOM_BUILDS ; do
		TARGET+="$i.build "
	done
fi

scream "Building \"$TARGET\"."

for i in $TARGET; do
  line=`"$READLINK" --canonicalize "$i"`
  WORKDIR=`echo "$line" | "$SED" 's/\.build$//'`
  cd "$WORKDIR"
  scream "********* Compiling $line...\n"
  . "$line" \
    && scream "********* ...$line successfully compiled and installed.\n" \
    || { 
      scream "********* ...$line " 
      failure
    }
  cd ..
  sudo PREFIX="$PREFIX" "$MN_DEPLOY_OVERLAY" -q
  echo "Compiled programs have been installed to $DESTDIR and deployed."
done

cd "$OLDWD"
