#!/bin/bash

. /medianet/lib/mn_includes

noroot

function platform_optimisations {
	echo "${CUSTOM_BUILD_GCCFLAGS[`get_platform`]}"
}

OLDWD=`pwd`
DESTDIR="$PREFIX"/overlay
cd "$PREFIX"/custom_builds

if [[ -n "$1" ]] ; then
	TARGET="$1.build"
else
	TARGET=
	for i in $CUSTOM_BUILDS ; do
		TARGET+="$i.build "
	done
fi

scream "Building \"$TARGET\"."

for i in $TARGET; do
  line=`"$READLINK" --canonicalize "$i"`
  WORKDIR=`echo "$line" | "$SED" 's/\.build$//'`
  cd "$WORKDIR"
  scream "********* Compiling $line...\n"
  . "$line" \
    && scream "********* ...$line successfully compiled and installed.\n" \
    || { 
      scream "********* ...$line " 
      failure
    }
  cd ..
  sudo PREFIX="$PREFIX" "$MN_DEPLOY_OVERLAY" -q
  echo "Compiled programs have been installed to $DESTDIR and deployed."
done

cd "$OLDWD"
