#!/bin/bash

. /medianet/lib/mn_includes

needroot

echo -n "Creating group medianet..."
"$GROUPADD" medianet && success || failure
echo -n "Creating home directory..."
"$MKDIR" /home/medianet && success || failure
echo -n "Creating user medianet..."
"$USERADD" -c "medianet Maintenance account" -g medianet -G users,audio,video,gpio,input -d /home/medianet medianet && success || failure
echo -n "Changing login shell to /bin/bash..."
"$CHSH" -s /bin/bash medianet && success || failure
echo -n "Creating .ssh dir..."
"$MKDIR" /home/medianet/.ssh && success || failure
echo -n "Installing public key for SSH authorization..."
"$CP" /medianet/medianet.pub /home/medianet/.ssh/authorized_keys && success || failure
echo -n "Changing ownership of home directory..."
"$CHOWN" -R medianet:medianet /home/medianet && success || failure
echo -n "Adding medianet user to sudoers..."
# prevent user lockout from permission breakage in the overlay tree by making a hard copy
"$CP" /medianet/overlay/etc/sudoers.d/10_medianet-nopasswd /etc/sudoers.d/00_medianet-nopasswd_dontbreakme && success || failure


