#!/bin/bash

. /medianet/lib/mn_includes

needroot

TARGET="/tmp"

echo -n "Trying to clean out /tmp before mounting over it..."
$MOUNTPOINT -q "$TARGET" && {
	failure "Something is already mounted here!"
} || {
	rm -rf "$TARGET"/* "$TARGET"/.??* && success || failure
}
