#!/bin/bash

. /medianet/lib/mn_includes

needroot

scream "Create user account:"

echo -n "Creating group $CONF_GROUP..."
"$GROUPADD" "$CONF_GROUP" && success || failure

echo -n "Creating home directory $CONF_HOME..."
"$MKDIR" "$CONF_HOME" && success || failure

echo -n "Creating user $CONF_USER..."
"$USERADD" \
	-c "medianet system user" \
	-g "$CONF_GROUP" \
	-G "$CONF_OTHERGROUPS" \
	-d "$CONF_HOME" "$CONF_USER" \
	&& success || failure

echo -n "Changing login shell to /bin/bash..."
"$CHSH" -s /bin/bash medianet && success || failure

echo -n "Creating .ssh dir..."
"$MKDIR" -m 700 "$CONF_HOME"/.ssh && success || failure

echo -n "Changing ownership of home directory..."
"$CHOWN" -R "$CONF_USER:$CONF_GROUP" "$CONF_HOME" && success || failure

echo -n "Adding $CONF_USER to sudoers..."
# prevent user lockout due to permission breakage in the overlay tree:
# make a hard file, not a symlink
cat << EOF > "/etc/sudoers.d/10-${CONF_USER}-pubkey" && success || failure
Defaults env_keep += "SSH_AUTH_SOCK"
medianet ALL=(ALL) ALL
EOF
