#!/bin/bash


. /medianet/lib/mn_includes

noroot

# from_FOO <URL> <dirname> <branch> <commit>
from_git() {
  if [[ ! -d "$2" ]] ; then
    echo -ne "Cloning $1 into $2..."
    "$GIT" clone -q "$1" "$2" || failure && success
  else
    echo -ne "Git repository exists. Updating..."
    cd "$2"
    "$GIT" pull || failure && success
    cd ..
  fi
  if [[ -n "$3" ]] ; then
    echo -ne "Switching to branch $3..."
    OLDWD="$PWD"
    cd "$2"
    "$GIT" checkout "$3" || failure && success
    if [[ -n "$4" ]] ; then
      echo -ne "Resetting to commit $4..."
      "$GIT" reset --hard "$4" || failure && success
    fi
    cd "$OLDWD"
  fi
}

from_tar() {
  echo "Installing tarball $1 to $2:"
  if [[ -d "$2" ]] ; then
    echo -ne "Removing existing directory $2..."
    "$RM" -rf "$2" || failure && success
  fi
  echo -ne "Creating empty directory $2..."
  "$MKDIR" "$2" || failure && success
  cd "$2"
  ALGO=
  case `basename "$1"` in
    *.gz|*.tgz)
      ALGO=z
      ;;
    *.bz2|*.tbz)
      ALGO=j
      ;;
    *.xz)
      ALGO=J
      ;;
  esac
  "$WGET" -q -O - "$1" | "$TAR" --strip-components=1 -x -$ALGO -f - || failure && success
  cd ..
}

from_package()
{
	echo -e "Installing packages ..."
	"$SUDO" "$APT" -qqy install --no-install-recommends "$@" || failure && success
}


OLDWD=`pwd`
CUSTOM_BUILD_DIR="$PREFIX"/custom_builds
cd "$CUSTOM_BUILD_DIR"

if [[ -n "$1" ]] ; then
	TARGET="$1.checkout"
else
	TARGET=
        for i in $CUSTOM_BUILDS ; do
                TARGET+="$i.checkout "
        done
fi

for i in $TARGET ; do
  scream "********* Checking out $i:"
  . "$i" \
    && echo "********* $i and dependencies successfully checked out to $CUSTOM_BUILD_DIR." \
    || { 
      echo "********* $i "
      bail
    }
    echo
done

cd "$OLDWD"

