#!/bin/bash


. /medianet/lib/mn_includes

noroot

# from_FOO <URL> <dirname>
from_git() {
  if [[ ! -d "$2" ]] ; then
    echo -ne "Cloning $1 into $2..."
    "$GIT" clone -q "$1" "$2" || failure && success
  else
    echo -ne "Git repository exists. Updating..."
    cd "$2"
    "$GIT" pull || failure && success
    cd ..
  fi
}

from_tar() {
  echo -ne "Installing tarball $1 to $2..."
  if [[ ! -d "$2" ]] ; then
    mkdir "$2"
  fi
  cd "$2"
  ALGO=
  case `basename "$1"` in
    *.gz|*.tgz)
      ALGO=z
      ;;
    *.bz2|*.tbz)
      ALGO=j
      ;;
    *.xz)
      ALGO=J
      ;;
  esac
  "$WGET" -q -O - "$1" | "$TAR" --strip-components=1 -x -$ALGO -f - || failure && success
  cd ..
}

from_package()
{
	echo -ne "Installing packages ..."
  	sudo "$APTGET" -qqy install --no-install-recommends "$@" || failure && success
}


OLDWD=`pwd`
CUSTOM_BUILD_DIR="$PREFIX"/custom_builds
cd "$CUSTOM_BUILD_DIR"

if [[ -n "$1" ]] ; then
	TARGET="$1.checkout"
else
	TARGET=
        for i in $CUSTOM_BUILDS ; do
                TARGET+="$i.checkout "
        done
fi

scream "Checking out \"$TARGET\"."

for i in $TARGET ; do
  scream "********* Checking out $i..."
  . "$i" \
    && scream "********* ... $i and dependencies successfully checked out." \
    || { 
      scream "********* ... $i "
      bail
    }
done

echo "Checked out sources have been installed to $CUSTOM_BUILD_DIR."
cd "$OLDWD"

