#!/bin/bash

. /medianet/lib/mn_includes

needroot

# This script deploys all files in the /medianet/overlay directory as symbolic links
# throughout the distribution file system.

OLDPWD=$PWD
# we're deploying the main overlay
cd "$PREFIX"/overlay

scream "Checking directory tree..."
# Iterate over all directories in overlay
for DIR in `find -P * -type d` ; do
	TARGET=/"$DIR"
	echo -n "$TARGET:"
	if [[ ! -d "$TARGET" && ! -L "$TARGET" ]] ; then
		echo -n " creating..."
		"$MKDIR" "$TARGET" && success || bail
		echo -en "\tsetting file permissions..."
		"$CHOWN" --reference "$DIR" "$TARGET"\
		&& "$CHMOD" --reference "$DIR" "$TARGET"\
		&& success || fail		
	else
		echo " exists."
	fi
done

scream "Deploying overlay..."
# Iterate over all files in overlay
for SOURCE in `find -P * \! -name README \! -name *~ \! -type d` ; do
	TARGET=/"$SOURCE"
	BACKUP=/"$SOURCE".mn_
	LINK="$PWD"/"$SOURCE"

	echo -ne "$TARGET:\t" 

	# Does a correct already exist from a previous run? Then don't stress the flash unneccessarily.
	LINKSTO=`"$READLINK" --canonicalize "$TARGET"`
	REALLINK=`"$READLINK" --canonicalize "$LINK"`
	if [[ "$REALLINK" = "$LINKSTO" ]] ; then
		echo -e "Unchanged."
		continue
	fi

	# Check if regular file or dir (not link, that would be us!)
	# exists in distribution file system, if so: back it up.
	if [[ ( -f "$TARGET" && ! -L "$TARGET" ) || ( -d "$TARGET" && ! -L "$TARGET" ) ]] ; then
		# Do not overwrite existing backups.
		if [[ ! -e "$BACKUP" ]] ; then
			echo -ne "Backing up. "
			"$MV" "$TARGET" "$BACKUP" || bail
		fi
	fi

	# Replace original file with symbolic link to medianet overlay.
	if [[ -e "$TARGET" || -L "$TARGET" ]] ; then
		echo -ne "Removing old file/link. "
                "$RM" -r "$TARGET" || failure
        fi
	echo -ne "Linking... "
	ln -Tn -r -s "$LINK" "$TARGET" && success || bail
done
cd "$OLDPWD"
