#!/bin/bash

. /medianet/lib/mn_includes

. $MEDIANETCONF

CONF=/boot/medianet.txt

echo "Boot options from $MEDIANETCONF:"
echo "$CONFIG_TXT_OPTIONS"
echo -n "Writing to $CONF..."
sudo bash -c "echo $CONFIG_TXT_OPTIONS > $CONF" > /dev/null || failure && success

echo -n "Checking if `basename $CONF` is included from config.txt..."
LINE="include `basename $CONF`"

if ! /bin/grep "$LINE" /boot/config.txt > /dev/null ; then
  echo -n " no. Including..."
  sudo bash -c "echo $LINE >> /boot/config.txt" || failure && success
else
  echo " yes."
fi

scream "Iterating over boot/:"

OLDPWD=`pwd`
cd /medianet/boot
for i in `/usr/bin/find -type f` ; do 
  echo -n "Checking if $i is already installed..."
  if ! cmp "$i" /boot/"$i" > /dev/null; then
    echo -n " no. Installing..."
    sudo cp "$i" /boot || failure && success
  else
    echo " yes."
  fi
done
cd $OLDPWD

  