#!/bin/bash

. /medianet/lib/mn_includes

needroot

echo "Boot options from $SYSTEM_CONFIG:"
echo "$CONFIG_TXT_OPTIONS"
echo -n "Writing to $CONF..."
echo "$CONFIG_TXT_OPTIONS" > "$CONF_FILE_BOOT" || failure && success

echo -n "Checking if `basename $CONF_FILE_BOOT` is included from config.txt..."
LINE="include `basename $CONF_FILE_BOOT`"

if ! "$GREP" "$LINE" /boot/config.txt > /dev/null ; then
  echo -n " no. Including..."
  echo "$LINE" >> /boot/config.txt || failure && success
else
  echo " yes."
fi

scream "Iterating over boot/:"

OLDPWD=`pwd`
cd "$PREFIX"/boot
for i in `"$FIND" -type f` ; do 
  echo -n "Checking if $i is already installed..."
  if ! "$CMP" "$i" /boot/"$i" > /dev/null; then
    echo -n " no. Installing..."
    "$CP" "$i" /boot || failure && success
  else
    echo " yes."
  fi
done
cd "$OLDPWD"
