#!/bin/bash

. /medianet/lib/mn_includes

needroot

echo "Disabling swap:"
if [[ -e "$DPHYSSWAPFILE" ]] ; then
	echo -n "Trying dphys-swapfile... "
	"$DPHYSSWAPFILE" swapoff && "$DPHYSSWAPFILE" uninstall && success || failure
else
	echo -n "Trying manual method... "
	"$SWAPOFF" -a && "$SED" -i '/^[^#]/ s/\(^.*swap.*$\)/#\ \1/' /etc/fstab && success || failure
fi
"$SYSTEMCTL" disable dphys-swapfile && success || failure


