#!/bin/bash

. /medianet/lib/mn_includes

BASEDIR=`dirname $0`/..

# This script deploys all files in the /medianet/overlay directory as symbolic links
# throughout the distribution file system.

OLDPWD=$PWD
# we're deploying the main overlay
cd "$BASEDIR"/overlay

scream "Checking directory tree..."
# Iterate over all directories in overlay
for DIR in `find -P * -type d` ; do
	TARGET=/"$DIR"
	echo -n "$TARGET:"
	if [[ ! -d "$TARGET" && ! -L "$TARGET" ]] ; then
		echo -n " creating..."
		sudo mkdir "$TARGET" && success || bail
		echo -en "\tsetting file permissions..."
		sudo chown --reference "$DIR" "$TARGET"\
		&& sudo chmod --reference "$DIR" "$TARGET"\
		&& success || fail		
	else
		echo " exists."
	fi
done

scream "Deploying overlay..."
# Iterate over all files in overlay
for SOURCE in `find -P * \! -name README \! -type d` ; do
	TARGET=/"$SOURCE"
	BACKUP=/"$SOURCE".mn_
	LINK="$PWD"/"$SOURCE"

	echo -ne "$TARGET:\t" 

	# Does a correct already exist from a previous run? Then don't stress the flash unneccessarily.
	LINKSTO=`readlink --canonicalize "$TARGET"`
	REALLINK=`readlink --canonicalize "$LINK"`
	if [[ "$REALLINK" = "$LINKSTO" ]] ; then
		echo -e "Unchanged."
		continue
	fi

	# Check if regular file or dir (not link, that would be us!)
	# exists in distribution file system, if so: back it up.
	if [[ ( -f "$TARGET" && ! -L "$TARGET" ) || ( -d "$TARGET" && ! -L "$TARGET" ) ]] ; then
		# Do not overwrite existing backups.
		if [[ ! -e "$BACKUP" ]] ; then
			echo -ne "backing up...\t"
			sudo mv "$TARGET" "$BACKUP" || bail
		fi
	fi

	# Replace original file with symbolic link to medianet overlay.
	if [[ -e "$TARGET" || -L "$TARGET" ]] ; then
		echo -ne "Removing old file/link...\t"
                sudo rm -r "$TARGET" || failure
        fi
	echo -ne "Linking...\t"
	sudo ln -Tn -r -s "$LINK" "$TARGET" && success || bail
done

cd "$OLDPWD"
