#!/bin/bash

. /medianet/lib/mn_includes

echo "Disabling swap:"
if [[ -n `which dphys-swapfile 2> /dev/null` ]] ; then
	echo -n "Trying dphys-swapfile... "
	sudo dphys-swapfile swapoff && sudo dphys-swapfile uninstall && success || failure
else
	echo -n "Trying manual method... "
	sudo swapoff -a && sudo sed -i '/^[^#]/ s/\(^.*swap.*$\)/#\ \1/' /etc/fstab && success || failure
fi

