#!/bin/bash

. /medianet/lib/mn_includes

needroot

echo -n "Killing all jobs owned by pi..."
"$PKILL" --signal KILL -u pi && success || failure
echo -n "Deleting user pi..."
"$USERDEL" pi && success || bail "Is the user still logged in?"
echo -n "Deleting sudo entry for pi..."
"$RM" /etc/sudoers.d/010_pi-nopasswd && success || failure
echo -n "Deleting home directory"
"$RM" rm -rf /home/pi/ && success || failure

echo "Locking password of root user. MAKE SURE YOU HAVE CREATED A SUDO-ENABLED USER ALREADY!"
read -n1 -r -p "Ok?" && "$PASSWD" -l root && success || failure

