#!/bin/bash

. /medianet/lib/mn_includes

needroot

echo -n "Looking for jobs owned by user pi..."
"$PGREP" -u pi | "$TR" '\n' ' ' && {
	echo -en "\nKilling all jobs owned by pi..."
	"$PKILL" --signal KILL -u pi && success || failure
} || echo "none."
echo -n "Deleting user pi..."
"$USERDEL" pi && success || {
	RETVAL=$?
	case "$RETVAL" in
	6)
		failure "User pi does not exist."
		;;
	8)
		failure "User pi is currently logged in."
		;;
	*)
		bail "Could not delete user pi (Error $RETVAL)."
		;;
	esac
}
echo -n "Deleting sudo entry for pi..."
"$RM" /etc/sudoers.d/010_pi-nopasswd && success || failure
echo -n "Deleting home directory"
"$RM" rm -rf /home/pi/ && success || failure

echo -n "Locking password of root user. Are you sure?"
yesno && "$PASSWD" -l root && success || failure "skipped"

