#!/bin/bash

. /medianet/lib/mn_includes

needroot

echo "Expanding /local partition on /dev/mmcblk0p3 to maximum size..."
"$PARTED" -m /dev/mmcblk0 resizepart 3 100% yes && success || failure
echo "Growing /local filesystem to partition size..."
"$RESIZE2FS" /dev/mmcblk0p3 && success || failure
