#!/bin/bash

. /medianet/lib/mn_includes

needroot

OLDWD="$PWD"
cd "$PREFIX"

echo -n "Changing ownership to $CONF_USER:$CONF_GROUP..."
"$CHOWN" -R "$CONF_USER":"$CONF_GROUP" /"$PREFIX" && success || failure

cd "$OLDWD"
