#!/bin/bash

. /medianet/lib/mn_includes

needroot

TIMEZONE="Europe/Berlin"
DEFAULTLOCALE="en_US.UTF-8"
OTHERLOCALES="en_GB.UTF-8 de_DE.UTF-8"

echo "Activating locales..."
for i in $DEFAULTLOCALE $OTHERLOCALES ; do
	echo -ne "\t$i"
	"$SED" -i "s/\#.*$i/$i/" /etc/locale.gen && success || failure
done

echo "Setting default locale to $DEFAULTLOCALE... "
echo "LANG=en_US.UTF-8" > /etc/default/locale && \
	"$DPKGRECONFIGURE" --frontend=noninteractive locales && \
	"$UPDATELOCALE" LANG=en_US.UTF-8 \
	&& success || bail

echo -n "Setting timezone to $TIMEZONE... "
echo "$TIMEZONE" > /etc/timezone \
	&& "$DPKGRECONFIGURE"-f noninteractive tzdata \
	&& success || bail
