#!/bin/bash

. /medianet/lib/mn_includes

needroot

scream "Installing early boostrap dependencies:"
"$APTGET" update

cat "$CONF_FILE_PACKAGES_EARLY" | while read line ; do
	for package in $line; do
		if [[ $package == \#* ]] ; then
			# we've found a comment, ignore all that follows on the line:
			break
		else
			echo -n "$package "
		fi
	done
done | "$XARGS" -n 32 "$APTGET" -y install
