#!/bin/bash

. /medianet/lib/mn_includes

needroot

scream "Populating persistant storage in /local:"

"$MOUNT" | "$GREP" "\s/local\s" || bail "No device mounted under /local." 

while read LINE ;  do
	echo $LINE | "$GREP" "^#" && continue # ignore comments
	echo $LINE | "$GREP" "^$" && continue # ignore empty lines 
	TASK=($LINE)
	echo -n "Creating directory ${TASK[0]} with mode ${TASK[3]}..."
	"$MKDIR" --parents --mode ${TASK[3]} ${TASK[0]} && success || failure
	echo -ne "\tChanging owner/group to ${TASK[1]}:${TASK[2]}..."
	"$CHOWN" -R ${TASK[1]}:${TASK[2]} ${TASK[0]} && success || failure
done <<< "$LOCALDIRS"

















