#!/bin/bash

. /medianet/lib/mn_includes

needroot

scream "Adding packages from $CONF_FILE_PACKAGES:"

echo "Updating package cache:"
"$APT" update

cat "$CONF_FILE_PACKAGES" | while read line ; do
	for package in $line; do
		if [[ $package == \#* ]] ; then
			# we've found a comment, ignore all that follows on the line:
			break
		else
			echo -n "$package "
		fi
	done
done | "$XARGS" -n 32 "$APT" -y install --no-install-recommends
