#!/bin/bash

. /medianet/lib/mn_includes

needroot

OLDPWD=`pwd`

cd "$BASEDIR"

echo -n  "Setting ownership of /medianet tree to medianet:medianet... "
"$CHOWN" -R medianet:medianet . || failure && success

cd "$OLDPWD"
