#!/bin/bash

. /medianet/lib/mn_includes

needroot

scream "Performing  base system update:"

echo -e "\n\nUpdating package libraries:\n"
"$APT" update
echo -e "\n\nUpgrading system:\n"
"$APT" upgrade