#!/bin/bash

. /medianet/lib/mn_includes

needroot

scream "Activating default configuration"

echo -n "Linking default configuration file..."
$LN -fs /medianet/config/BuiltInAudio /medianet/config/this && success || failure

echo "Running config updater manually:"
/medianet/overlay/usr/local/bin/mn_config_update
