#!/bin/bash

. /medianet/lib/mn_includes

needroot

# This helper creates a unique machine ID for DBUS.

MID=`/usr/bin/dbus-uuidgen`
# see https://unix.stackexchange.com/questions/191313/why-is-my-systemd-journal-not-persistent-across-reboots
echo -n "Unmounting /etc/machine-id..."
umount /etc/machine-id && success || failure
echo -n "Setting machine ID to new random value \'$MID\'..."
echo "$MID" > /etc/machine-id && success || failure
echo -n "Setting read-only..."
"$CHMOD" 444 /etc/machine-id && success || failure
