#!/bin/bash

. /medianet/lib/mn_includes

needroot

OLDPWD=`pwd`

cd "$PREFIX"

echo -n  "Setting ownership of $PREFIX tree to medianet:medianet... "
"$CHOWN" -R medianet:medianet . || failure && success

cd "$OLDPWD"
