#!/bin/bash

. /medianet/lib/mn_includes

needroot

OLDPWD=`pwd`
# settings to use if no rule is found in $CONF_FILE_PERMISSIONS:
DEFOWNER="root:root"
DEFPERMS="u=rwX,g=rX,o=rX"

cd "$PREFIX"

declare -A OWNER
declare -A PERMS

scream "Setting permissions from $CONF_FILE_PERMISSIONS:"

PERM_LIST=`$CAT "$CONF_FILE_PERMISSIONS" \
	| $SED "s/'\(.*\)'[[:space:]]\{1,\}\([[:alnum:]-]*:[[:alnum:]-]*\)[[:space:]]\{1,\}\([0-9]\{3,4\}\)[[:space:]]*/\1\n\2\n\3/"`

while read FILE ; do
#  echo "File '$FILE'" 
  read O
  OWNER["$FILE"]="$O"
#  echo Owner ${OWNER["$FILE"]}
  read P
  PERMS["$FILE"]="$P"
#  echo Perms ${PERMS["$FILE"]}
done <<< $PERM_LIST

# HACK: fix sudoers first to avoid a warning on each subsequent action:
for QUERY in "overlay/etc/sudoers.d" "-P overlay/ boot/ ! -type l"; do

  while read FILE ; do
  
    echo -ne "$FILE:\n\t"

    if [[ -n "$FILE" ]] ; then
      OWNER_RULE=${OWNER["$FILE"]}
    else
      continue
    fi
    if [[ -n "$OWNER_RULE" ]] ; then
      PERMS_RULE=${PERMS["$FILE"]}
      CUROWNER=`"$STAT" -c "%U:%G" "$FILE"`
      CURPERMS=`"$STAT" -c "%a" "$FILE"`
      if [[ "$CUROWNER" != "$OWNER_RULE" ]] ; then
        echo -ne "Owner to $OWNER_RULE. "
        "$CHOWN" "$OWNER_RULE" "$FILE" || failure
      else 
        echo -ne "Owner ok. "
      fi
      if [[ "$CURPERMS" != "$PERMS_RULE" ]] ; then
        echo -ne "Permissions to $PERMS_RULE..."
        "$CHMOD" "$PERMS_RULE" "$FILE" || failure
      else
        echo -ne "Permissions ok."
      fi
    else
      echo -ne "No rule. "
      echo -ne "Setting to default $DEFOWNER"
      "$CHOWN" "$DEFOWNER" "$FILE" || failure
      echo -ne " $DEFPERMS..."
      "$CHMOD" "$DEFPERMS" "$FILE" || failure 
    fi
    echo

  done <<< $($FIND $QUERY)
 
done

cd "$OLDPWD"
