#!/bin/bash

. /medianet/lib/mn_includes

needroot

scream "Activating default configuration"

echo -n "Installting default configuration file to $SYSTEM_CONFIG_DIR, edit to taste..."
$CP -fs /medianet/config/BuiltInAudio/* $SYSTEM_CONFIG_DIR/ && success || failure

