#!/bin/bash

. /medianet/lib/mn_includes

BASEDIR=`dirname $0`

OLDPWD=`pwd`
PERMFILE="permissions.medianet"
# settings to use if no rule is found in $PERMFILE:
DEFOWNER="root:root"
DEFPERMS="u=rwX,g=rX,o=rX"

cd "$BASEDIR"/../

# HACK: fix sudoers first to avoid a warning on each subsequent action:
for FILE in `sudo find overlay/etc/sudoers.d` `sudo find -P overlay/ boot/ ! -type l `; do
  
  echo -ne "$FILE:\n\t"
  
  RULE=`grep -E "^.$FILE." $PERMFILE`
  if [[ -n "$RULE" ]] ; then
    OWNER=`echo $RULE | cut -d ' ' -f 2`
    PERMS=`echo $RULE | cut -d ' ' -f 3`
    CUROWNER=`stat -c "%U:%G" "$FILE"`
    CURPERMS=`stat -c "%a" "$FILE"`
    if [[ "$CUROWNER" != "$OWNER" ]] ; then
      echo -ne "Owner to $OWNER. "
      sudo chown "$OWNER" "$FILE" || failure
    else 
      echo -ne "Owner ok. "
    fi
    if [[ "$CURPERMS" != "$PERMS" ]] ; then
      echo -ne "Permissions to $PERMS..."
      sudo chmod "$PERMS" "$FILE" || failure
    else
      echo -ne "Permissions ok."
    fi
  else
    echo -ne "No rule. "
    echo -ne "Setting to default $DEFOWNER"
    sudo chown "$DEFOWNER" "$FILE" || failure
    echo -ne " $DEFPERMS..."
    sudo chmod "$DEFPERMS" "$FILE" || failure 
  fi
  echo
done

cd $OLDPWD
