#!/bin/bash

. /medianet/lib/mn_includes

needroot

scream "sudo setup:"

echo "Remove default NOPASSWD setting(s)..."
for i in $("$GREP" -ril nopasswd /etc/sudoers.d/*) ; do
	echo -n "Found $i - deleting..." | indent
	"$RM" -f "$i" && success || failure
done

echo -n "Adding $CONF_USER to sudoers..."
# prevent user lockout due to permission breakage in the overlay tree:
# make a hard file, not a symlink
cat << EOF > "/etc/sudoers.d/10-${CONF_USER}-pubkey" && success || failure
Defaults env_keep += "SSH_AUTH_SOCK"
medianet ALL=(ALL) ALL
EOF
