#!/bin/bash

. /medianet/lib/mn_includes

OLDPWD=`pwd`
scream "Updating $CONF_FILE_PERMISSIONS:"
cd "$PREFIX"
mv "$CONF_FILE_PERMISSIONS" "$CONF_FILE_PERMISSIONS".old
"$FIND" overlay boot ! -type l ! -name "*~" ! -name ".gitkeep" -exec "$STAT" -c "%N %U:%G %a" {} \; >> "$CONF_FILE_PERMISSIONS"
cd "$OLDPWD"
